apiVersion: v1
kind: Service
metadata:
  name: tuxedo-bankapp-svc
  labels:
    {{- include "tuxedo-bankapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5955
      protocol: TCP
      name: http
  selector:
    app: tuxedo-bankapp
