# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.domain.domainName }}-delete-soa-infra-domain-job
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded  
spec:  
  template:
    metadata:
      labels:
        weblogic.domainUID: {{ .Values.domain.domainName }}
        weblogic.domainName: {{ .Values.domain.domainName }}
        app: {{ .Values.domain.domainName }}-delete-soa-infra-domain-job
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "soa-suite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: delete-soa-infra-domain-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7001
          volumeMounts:
          - mountPath: {{ .Values.domain.rootDir }}
            name: soa-infra-domain-storage-volume
          command:
            - /bin/bash
            - -c
            - rm -rf ${DOMAIN_DIR} && rm -rf ${DOMAIN_LOGS_DIR}
          env:
            - name: DOMAIN_DIR
              value: "{{ .Values.domain.rootDir }}/domains/{{ .Values.domain.domainName }}"
            - name: DOMAIN_LOGS_DIR
              value: "{{ .Values.domain.rootDir }}/logs/{{ .Values.domain.domainName }}"
      volumes:
        - name: soa-infra-domain-storage-volume
          persistentVolumeClaim:
            claimName: {{ .Values.domain.domainName }}-domain-pvc
