# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# This is a template for RCU Pod
#
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: rcu
    {{- include "soa-suite.labels" . | nindent 4 }}
  name: {{ .Values.domain.domainName }}-rcu-delete
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded  
spec:
  template:
    metadata:
      labels:
        weblogic.domainUID: {{ .Values.domain.domainName }}
        weblogic.domainName: {{ .Values.domain.domainName }}
        app: {{ .Values.domain.domainName }}-rcu-delete
        {{- include "soa-suite.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "soa-suite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - command:
        - /bin/bash
        - -c
        - |-
          /u01/oracle/oracle_common/bin/rcu -silent -dropRepository \
          -databaseType ORACLE -connectString ${connectString} \
          -dbUser sys  -dbRole sysdba \
          -selectDependentsForComponents true \
          -schemaPrefix ${schemaPrefix} ${extComponents} ${extVariables}  \
          -component MDS -component IAU -component IAU_APPEND -component IAU_VIEWER \
          -component OPSS  -component WLS -component STB << EOF
          ${sysPassword} 
          ${schemaPassword}
          EOF
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}-rcu
        env:
          - name: connectString
            value: "{{ (include "soa-suite.databaseUrl" .) }}"
          - name: schemaPrefix
            value: {{ .Values.domain.rcuSchema.prefix }}
          - name: schemaProfileType
            value: {{ .Values.domain.rcuSchema.profileType }}
          - name: sysPassword
            valueFrom:
              secretKeyRef:
                {{- if .Values.oracledb.credentials.secretName }}
                name: {{ .Values.oracledb.credentials.secretName }}
                {{- else }}
                name: {{ .Values.domain.domainName }}-db-credentials
                {{- end }}
                key: password
          - name: schemaPassword
            valueFrom:
              secretKeyRef:
                {{- if .Values.domain.rcuSchema.credentials.secretName }}
                name: {{ .Values.domain.rcuSchema.credentials.secretName }}
                {{- else }}
                name: {{ .Values.domain.domainName }}-rcu-credentials
                {{- end }}
                key: password
          {{- if eq .Values.domain.type "fmw" }}
          - name: extComponents
            value: ""
          - name: extVariables
            value: ""
          {{- end }}
          {{- if (eq .Values.domain.type "osb") }}
          - name: extComponents
            value: "-component SOAINFRA"
          - name: extVariables
            value: "-variables SOA_PROFILE_TYPE=$(schemaProfileType),HEALTHCARE_INTEGRATION=NO"
          {{- end }}
          {{- if or (eq .Values.domain.type "soaosb") (eq .Values.domain.type "soa") }}
          - name: extComponents
            value: "-component SOAINFRA -component ESS"
          - name: extVariables
            value: "-variables SOA_PROFILE_TYPE=$(schemaProfileType),HEALTHCARE_INTEGRATION=NO"
          {{- end }}
        
        startupProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - java utils.dbping ORACLE_THIN "sys as sysdba" ${sysPassword} ${connectString}
          failureThreshold: 30
          periodSeconds: 10

