---
name: Lint new or modified Markdown files

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  lint-markdown-files:
    name: Lint Markdown files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run markdownlint
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
