---
name: Lint new or modified shell scripts

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  lint-shell-scripts:
    name: Lint shell scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run shellcheck/shellfmt
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
